---
- name: show interface information
  hosts: cisco
  gather_facts: no

  tasks:
    - name: Gather legacy and resource facts
      cisco.ios.ios_facts:
        gather_subset: bgp_global
        gather_network_resources: all