---
- name: show interface information
  hosts: cisco
  gather_facts: no

  tasks:
    - name: Gather L2 interfaces resource and minimal legacy facts
      cisco.ios.ios_facts:
        gather_subset: min
        gather_network_resources: l2_interfaces
