---
- name: show interface information
  hosts: cisco
  gather_facts: no

  tasks:
    - name: Gather only the interfaces resource facts and no legacy facts
      cisco.ios.ios_facts:
        gather_subset:
          - '!all'
          - '!min'
        gather_network_resources:
          - interfaces
